[http]
listen_socket = "0.0.0.0:8080"

[positions]
positions = [
    [
    0,
    0,
],
    [
    0,
    100,
],
    [
    100,
    0,
],
    [
    100,
    100,
],
    [
    200,
    0,
],
    [
    200,
    100,
],
    [
    300,
    0,
],
    [
    300,
    100,
],
]

[camera]
video_path = "/dev/video0"

[yolo]
model_path = "./best.safetensors"
model_size = "N"
num_classes = 3
nms_threshold = 0.5
acc_threshold = 0.5

[watering]
interval = 0
pin= { chip = "/dev/gpiochip3", line = 25 }

[linear_x]
reverse = false
min_mm_per_s = 5
max_mm_per_s = 200
accelerate = 100
step_per_ms = 40
en_pin= { chip = "/dev/gpiochip0", line = 24 }
dir_pin= { chip = "/dev/gpiochip4", line = 7 }
step_pin= { chip = "/dev/gpiochip4", line = 6 }

[linear_y]
reverse = false
min_mm_per_s = 5
max_mm_per_s = 200
accelerate = 100
step_per_ms = 40
en_pin= { chip = "/dev/gpiochip0", line = 25 }
dir_pin= { chip = "/dev/gpiochip4", line = 1 }
step_pin= { chip = "/dev/gpiochip4", line = 3 }

