[http]
listen_socket = "0.0.0.0:8080"

[positions]
positions=[
	[0,0],[125,0],[245,0],[350,0],
	[0,120],[125,120],[245,120],[350,120],
	[85,220]
]

[camera]
video_path = "/dev/videoAGV"

[yolo]
model_path = "./best.safetensors"
model_size = "N"
num_classes = 3
nms_threshold = 0.5
acc_threshold = 0.5

[watering]
interval = 0
pin= { chip = "/dev/gpiochipAGV", line = 7 }

[linear2d.en_pin]
chip = "/dev/gpiochipAGV"
line = 2

[linear2d.linear_x]
reverse = true
min_mm_per_s = 5
max_mm_per_s = 200
accelerate = 100
step_per_ms = 40
step_pin= { chip = "/dev/gpiochipAGV", line = 3 }
dir_pin= { chip = "/dev/gpiochipAGV", line = 4 }

[linear2d.linear_y]
reverse = true
min_mm_per_s = 5
max_mm_per_s = 200
accelerate = 100
step_per_ms = 40
step_pin= { chip = "/dev/gpiochipAGV", line = 5 }
dir_pin= { chip = "/dev/gpiochipAGV", line = 6 }

