[package]
name = "agrivision"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.4.2", features = [ "derive" ] }
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
serde_json = "1.0.105"
tide = "0.16.0"
anyhow = "1.0.75"
rppal = "0.16.0"
base58 = "0.2.0"
rand = "0.8.5"
candle-core = "0.3.1"
candle-nn = "0.3.1"
image = "0.24.7"
candle-transformers = "0.3.1"
tracing = "0.1.40"
once_cell = "1.19.0"
ureq = { version = "2.9.1", default-features = false }
log = "0.4.20"
simple_logger = "4.3.0"
v4l = "0.14.0"
async-broadcast = "0.6.0"
pin-project-lite = "0.2.13"
futures-lite = "2.1.0"
async-channel = "2.1.1"
url = "2.5.0"
toml = "0.8.8"
gpio-cdev = "0.6.0"
