[actuators.en_pin]
chip = "stub"
line = 2

[actuators.linear_x]
reverse = false
limit = 200
position = 0
min_mm_per_s = 10
max_mm_per_s = 50
step_per_mm = 40

[actuators.linear_x.step_pin]
chip = "stub"
line = 3

[actuators.linear_x.dir_pin]
chip = "stub"
line = 4

[actuators.linear_y]
reverse = false
limit = 200
position = 100
min_mm_per_s = 10
max_mm_per_s = 50
step_per_mm = 40

[actuators.linear_y.step_pin]
chip = "stub"
line = 5

[actuators.linear_y.dir_pin]
chip = "stub"
line = 6

[actuators.watering.pin]
chip = "stub"
line = 7

[actuators.camera]
video_path = "/dev/video0"
video_orientation = "Normal"

[detector.Robo]
project_name = "agrivision_mushroom"
version = 5
api_key = "06U7b6ebhq7PBXeOCs59"
