[vision]
path = ""
size = "N"
num_classes = 0
nms_threshold = 0.0
acc_threshold = 0.0
interval = 0

[camera.local_camera]
camera_id = 0

[restapi]
port = 0

[linear_actuators.x]
reversed = false
en_pin.chip = ""
en_pin.line = 0
diag_pin.chip = ""
diag_pin.line = 0
step_pin.chip = ""
step_pin.line = 0
dir_pin.chip = ""
dir_pin.line = 0

[linear_actuators.y]
reversed = false
en_pin.chip = ""
en_pin.line = 0
diag_pin.chip = ""
diag_pin.line = 0
step_pin.chip = ""
step_pin.line = 0
dir_pin.chip = ""
dir_pin.line = 0

[linear_actuators.z]
reversed = false
en_pin.chip = ""
en_pin.line = 0
diag_pin.chip = ""
diag_pin.line = 0
step_pin.chip = ""
step_pin.line = 0
dir_pin.chip = ""
dir_pin.line = 0
